import type { Metadata } from "next";
import "./globals.css";
import { Outfit } from "next/font/google";

const Font = Outfit({ subsets: ["latin"], weight: ['100', '200','300','400','600','700','800']});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={Font.className}>{children}</body>
    </html>
  );
}
